products = [
    {
        "_id": "1",
        "name": "MIUTULARUTE 5",
        "image": "/images/Product_images/0.1.webp",
        "description": "Harness the power of interstellar communication with this device, featuring quantum bluetooth connectivity for seamless link-ups across galaxies. Experience high-fidelity audio holograms and a built-in translator for over 1,000 languages, including those of distant worlds.",
        "brand": "GalactiCorp",
        "category": "ELECTRONICS",
        "price": 59.99,
        "countInStock": 6,
        "rating": 4.5,
        "numReviews": 20,
    },
    {
        "_id": "2",
        "name": "SPEAK-ME 75 BAKER 5-BR KNWDGE",
        "image": "/images/Product_images/0.webp",
        "description": "A pocket-sized oracle offering insights from across the cosmos. This device not only captures celestial images but also provides an analysis of cosmic phenomena. Its triple-lens quantum camera pierces through the fabric of space-time, while ensuring an epic leap in energy sustainability.",
        "brand": "CelestialTech",
        "category": "ELECTRONICS",
        "price": 789.99,
        "countInStock": 0,
        "rating": 4.0,
        "numReviews": 5,
    },
    {
        "_id": "3",
        "name": "EXISTANCE 2000N",
        "image": "/images/Product_images/1.webp",
        "description": "Transcend ordinary photography with this device, designed for capturing the essence of being across multiple dimensions. Its multi-reality focusing systems and an intuitive design make it ideal for documenting the unseen wonders of the universe.",
        "brand": "EonTech",
        "category": "ELECTRONICS",
        "price": 849.99,
        "countInStock": 3,
        "rating": 3,
        "numReviews": 8,
    },
    {
        "_id": "4",
        "name": "LINGATOR 20 FRIPLE ARB 4",
        "image": "/images/Product_images/2.webp",
        "description": "The ultimate portal to a multiverse of entertainment, this device offers immersive gaming, holographic HD movies, interdimensional television, and music from across the galaxies. A gateway to experiencing the universe's vast cultures from the comfort of your habitat.",
        "brand": "NebulaDynamics",
        "category": "ELECTRONICS",
        "price": 479.99,
        "countInStock": 7,
        "rating": 5,
        "numReviews": 6,
    },
    {
        "_id": "5",
        "name": "ZREBA TE 76-MR",
        "image": "/images/Product_images/3.webp",
        "description": "Enhance your gaming experience with this telekinetic mouse, featuring LIGHTSYNC technology to sync with your neural patterns for unparalleled control. Customize your gameplay with six programmable functions, telepathically tuned for a fluid playing experience.",
        "brand": "XenoGamer",
        "category": "ELECTRONICS",
        "price": 29.99,
        "countInStock": 2,
        "rating": 3.5,
        "numReviews": 15,
    },
    {
        "_id": "6",
        "name": "ARETS MIATON 20054FS",
        "image": "/images/Product_images/4.webp",
        "description": "Meet the Echo Dot of the future - A compact quantum smart speaker woven with fabric from the moons of Jupiter. Designed for small spaceships and intergalactic habitats, it connects you with the universal knowledge network.",
        "brand": "GalactiCorp",
        "category": "ELECTRONICS",
        "price": 19.99,
        "countInStock": 8,
        "rating": 4,
        "numReviews": 9,
    },
    {
        "_id": "7",
        "name": "PLUOR 20 SF FL-002",
        "image": "/images/Product_images/5.webp",
        "description": "Immerse yourself in the rhythms of the cosmos with the Pluggenator 20 SF FL-002. Its harmonious frequencies resonate with the vibrations of distant stars, offering a transcendent auditory experience.",
        "brand": "CelestialTech",
        "category": "ELECTRONICS",
        "price": 99.99,
        "countInStock": 4,
        "rating": 4,
        "numReviews": 17,
    },
    {
        "_id": "8",
        "name": "LETIR 53SF-CV ",
        "image": "/images/Product_images/6.webp",
        "description": "Unleash the power of cosmic connectivity with Locacaratir 53SF-CV. Its quantum entanglement technology allows you to traverse the vastness of space-time effortlessly, bridging the gaps between distant worlds.",
        "brand": "EonTech",
        "category": "ELECTRONICS",
        "price": 39.99,
        "countInStock": 1,
        "rating": 4,
        "numReviews": 25,
    },
    {
        "_id": "9",
        "name": "MICROSCOPE BUT ALIEN!!",
        "image": "/images/Product_images/7.webp",
        "description": "Peer into the microscopic realms of the cosmos with the Microscope But Alien!! Its advanced alien optics reveal the intricate beauty of quantum particles, unlocking the mysteries of the universe at a subatomic level.",
        "brand": "NebulaDynamics",
        "category": "ELECTRONICS",
        "price": 109.99,
        "countInStock": 5,
        "rating": 4,
        "numReviews": 3,
    },
    {
        "_id": "10",
        "name": "BREDIATIR OF SHIRTAKA",
        "image": "/images/Product_images/8.webp",
        "description": "Channel the ancient energies of Shirtaka with the Brediatir of Shirtaka. This mystical artifact grants you insights into the cosmic forces that shape the universe, guiding you on your journey through the stars.",
        "brand": "CelestialTech",
        "category": "ELECTRONICS",
        "price": 59.99,
        "countInStock": 0,
        "rating": 4,
        "numReviews": 14,
    },
    {
        "_id": "11",
        "name": "MIUTULARUTE DOT 7FD FN",
        "image": "/images/Product_images/9.webp",
        "description": "Elevate your interstellar communications with the MIUTULARUTE DOT 7FD FN. Its quantum transceiver technology ensures crystal-clear transmissions across vast cosmic distances, connecting you with civilizations beyond the stars.",
        "brand": "GalactiCorp",
        "category": "ELECTRONICS",
        "price": 149.99,
        "countInStock": 2,
        "rating": 4,
        "numReviews": 18,
    },
    {
        "_id": "12",
        "name": "MICROWAVE NZ=6500 XM",
        "image": "/images/Product_images/10.webp",
        "description": "Experience culinary innovation from beyond the stars with the Microwave NZ=6500 XM. Its quantum cooking technology redefines gastronomic boundaries, allowing you to create cosmic delicacies that defy earthly conventions.",
        "brand": "NebulaDynamics",
        "category": "ELECTRONICS",
        "price": 2597.43,
        "countInStock": 10,
        "rating": 4,
        "numReviews": 11,
    },
    {
        "_id": "13",
        "name": "StellarChef Prodigy XG9",
        "image": "/images/Product_images/11.webp",
        "description": "Dive into the universe's culinary secrets with the StellarChef Prodigy XG9. Engineered with dark matter heating elements, this microwave offers instantaneous, evenly distributed heat, ensuring your space delicacies are cooked to perfection without altering their molecular integrity. Perfect for chefs who dare to experiment with flavors from across the galaxies.",
        "brand": "CosmicCuisine",
        "category": "Galactic Kitchenware",
        "price": 3299.99,
        "countInStock": 8,
        "rating": 4.8,
        "numReviews": 15,
    },
    {
        "_id": "14",
        "name": "Quantum Brewmaster 3000",
        "image": "/images/Product_images/12.webp",
        "description": "The Quantum Brewmaster 3000 revolutionizes your beverage experience, using subatomic vibration technology to enhance flavor profiles. Enjoy drinks cold or hot, from any planet, with molecular precision that preserves the original essence and adds a cosmic twist.",
        "brand": "NebulaDynamics",
        "category": "Electronics",
        "price": 2899.50,
        "countInStock": 12,
        "rating": 4.5,
        "numReviews": 18,
    },
    {
        "_id": "15",
        "name": "Galactic Guardian DX",
        "image": "/images/Product_images/13.webp",
        "description": "Ensure your home’s safety with the Galactic Guardian DX, utilizing quantum encryption to protect against physical and digital threats. With AI-powered surveillance that adapts to potential dangers from any universe, your peace of mind is guaranteed.",
        "brand": "SecureStars",
        "category": "Home Security",
        "price": 4100.00,
        "countInStock": 5,
        "rating": 4.9,
        "numReviews": 21,
    },
    {
        "_id": "16",
        "name": "AstroLight Projector LX",
        "image": "/images/Product_images/14.webp",
        "description": "Transform your space into a cosmic vista with the AstroLight Projector LX. This device paints your room with lights from galaxies far away, complete with customizable constellations. Experience the universe from the comfort of your home.",
        "brand": "CelestialVisions",
        "category": "Electronics",
        "price": 750.99,
        "countInStock": 20,
        "rating": 4.3,
        "numReviews": 8,
    },
    {
        "_id": "17",
        "name": "VoidSound Mini Sphere",
        "image": "/images/Product_images/15.webp",
        "description": "Immerse yourself in the sounds of the cosmos with the VoidSound Mini Sphere. This compact, levitating speaker uses zero-gravity sound waves to deliver pure, unaltered audio as if you’re listening to the music of the spheres themselves.",
        "brand": "NebulaAcoustics",
        "category": "Electronics",
        "price": 599.99,
        "countInStock": 15,
        "rating": 4.7,
        "numReviews": 25,
    },
    {
        "_id": "18",
        "name": "Photon Mixer EX",
        "image": "/images/Product_images/16.webp",
        "description": "Blend flavors from across the universe with the Photon Mixer EX. Its light-speed blades can mix, chop, and blend ingredients from any planet, ensuring your culinary creations are as boundless as your imagination.",
        "brand": "GalacticGourmet",
        "category": "Kitchen Appliances",
        "price": 1300.75,
        "countInStock": 7,
        "rating": 4.6,
        "numReviews": 14,
    },
    {
        "_id": "19",
        "name": "Interstellar Instant Cooker",
        "image": "/images/Product_images/17.webp",
        "description": "Fast-forward your cooking with the Interstellar Instant Cooker. Utilizing wormhole technology, it reduces cooking times by linking directly to the heat of distant stars, delivering energy-efficient, perfectly cooked meals every time.",
        "brand": "CosmoCulinary",
        "category": "Galactic Kitchenware",
        "price": 2200.00,
        "countInStock": 10,
        "rating": 5.0,
        "numReviews": 12,
    },
    {
        "_id": "20",
        "name": "Nebular Navigator 2X",
        "image": "/images/Product_images/18.webp",
        "description": "Explore the cosmos with unparalleled clarity using the Nebular Navigator 2X. This advanced telescope integrates quantum lensing technology, allowing you to view distant galaxies in real-time, with AI-enhanced celestial tracking to navigate the stars effortlessly.",
        "brand": "StargazeTech",
        "category": "Astronomy",
        "price": 4999.99,
        "countInStock": 4,
        "rating": 4.9,
        "numReviews": 19,
    },
    {
        "_id": "21",
        "name": "CosmicCleanse Air Purifier",
        "image": "/images/Product_images/19.webp",
        "description": "Breathe the purity of space with the CosmicCleanse Air Purifier. Utilizing a filtration system powered by micro-black hole technology, it eradicates pollutants, allergens, and microscopic impurities, recreating the pristine atmosphere of a distant, uninhabited planet in your living space.",
        "brand": "PureAtmos",
        "category": "Home Appliances",
        "price": 850.00,
        "countInStock": 20,
        "rating": 4.7,
        "numReviews": 22,
    },
]
